import type { ServerPreset } from "./types";

export const SERVER_PRESETS: ServerPreset[] = [
  {
    id: "newapi_standard",
    label: "NewAPI Standard",
    description: "Single-group server with optional ratio_config endpoint and header-based auth.",
    config: {
      presetId: "newapi_standard",
      type: "newapi",
      supportsGroupChain: false,
      groupSelectionMode: "single",
      groupMatchMode: "union",
      tokenUpdateMode: "newapi_put",
      tokenSearchMode: "search_by_keyword_then_match",
      logResolveMode: "token_name_lookup",
      ratioConfigEnabled: true,
      authMode: "header",
      authUserHeader: "New-Api-User",
      pricingPath: "/api/pricing",
      ratioConfigPath: "/api/ratio_config",
      logPath: "/api/log/self",
      tokenSearchPath: "/api/token/search",
      tokenUpdatePath: "/api/token/",
      groupsPath: "/api/user/self/groups",
      normalizerHintJson: JSON.stringify(
        {
          pricingDataPath: "data",
          ratioMode: "separate_ratio_endpoint",
          groupSelectionMode: "single",
          requestScaledQuotaType: 1,
        },
        null,
        2,
      ),
    },
  },
  {
    id: "rixapi_inline",
    label: "RixAPI Inline Ratio",
    description: "Chain-capable server where group ratios and price info are embedded in pricing payload.",
    config: {
      presetId: "rixapi_inline",
      type: "rixapi",
      supportsGroupChain: true,
      groupSelectionMode: "chain",
      groupMatchMode: "union",
      tokenUpdateMode: "rixapi_put",
      tokenSearchMode: "search_by_keyword_then_match",
      logResolveMode: "token_name_lookup",
      ratioConfigEnabled: false,
      authMode: "header",
      authUserHeader: "New-Api-User",
      pricingPath: "/api/pricing",
      logPath: "/api/log/self",
      tokenSearchPath: "/api/token/search",
      tokenUpdatePath: "/api/token/",
      groupsPath: "/api/token/group",
      normalizerHintJson: JSON.stringify(
        {
          pricingDataPath: "data.model_info",
          groupInfoPath: "data.group_info",
          ratioMode: "inline_group_ratio",
          groupSelectionMode: "chain",
          requestScaledQuotaType: 1,
        },
        null,
        2,
      ),
    },
  },
  {
    id: "custom_manual",
    label: "Custom Manual",
    description: "Blank starting point for unknown providers or partially compatible APIs.",
    config: {
      presetId: "custom_manual",
      type: "custom",
      supportsGroupChain: false,
      groupSelectionMode: "single",
      groupMatchMode: "union",
      tokenUpdateMode: "custom",
      tokenSearchMode: "custom",
      logResolveMode: "custom",
      ratioConfigEnabled: false,
      authMode: "none",
      pricingPath: "/api/pricing",
      logPath: "/api/log/self",
      tokenSearchPath: "/api/token/search",
      tokenUpdatePath: "/api/token/",
      groupsPath: "/api/groups",
      normalizerHintJson: JSON.stringify(
        {
          pricingDataPath: "",
          ratioMode: "custom",
          groupSelectionMode: "single",
          notes: "Fill your own mapping rules here, then validate them in Control Center > Normalizer Lab.",
        },
        null,
        2,
      ),
    },
  },
];

export function getServerPreset(id?: string) {
  return SERVER_PRESETS.find((preset) => preset.id === id);
}
